ALTER TABLE housing_background ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE housing_wall ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE housing_floor ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE housing_avatar ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE housing_furniture ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE housing_room ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;
